name    'puppet-rabbitmq'
version '2.0.0'
author  'Luis Hdez <luis.munoz.hdez@gmail.com>'
license 'MIT'
project_page 'http://www.aggressivex.com'
source  'https://github.com/aggressivex/puppet-rabbitmq'
summary 'Puppet module for rabbitmq'
description 'This module installs and manages rabbitmq following Example42 modules. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'example42/monitor', '>= 2.0.0'
dependency 'example42/firewall', '>= 2.0.0'
